### ISSUE TITLE
We need Travis integration

### ISSUE THREAD

**Issue by mrkrstphr** [illacceptanything/illacceptanything#363] opened 2015-04-08 12:52 UTC

**Comment by QamarWaqar** [comment] 2015-04-08 13:13
Agreed.

**Comment by rikas** [comment] 2015-04-08 13:18
+1

**Comment by ValkyrieUK** [comment] 2015-04-08 13:23
:+1:

**Comment by ProgVal** [comment] 2015-04-08 13:25
Duplicate of #184

**Closed** 2015-04-08 13:26 UTC
Labels: duplicate
