### ISSUE TITLE
Someone please implement!!

### ISSUE THREAD

**Issue by mrkrstphr** [illacceptanything/illacceptanything#360] opened 2015-04-08 12:32 UTC
Someone please utilize this in the gh-pages branch. kthx:

http://code.divshot.com/geo-bootstrap/

**Comment by ProgVal** [comment] 2015-04-08 13:27
Duplicate of #352

**Comment by MiLk** [comment] 2015-04-10 13:12
https://github.com/illacceptanything/illacceptanything.github.io/pulls

**Closed by MiLk** 2015-04-10 13:12 UTC
